name: Docker Image Express

on:
  push:
    branches: [ workflow ]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: development 
    strategy:
      matrix:
        node-version: [ 18.x, 20.x ]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - run: npm ci
    - run: npm test

  build:
    runs-on: ubuntu-latest
    environment: development 
    needs: [ test ]
    steps:
    - uses: actions/checkout@v4
    - name: Docker build to registry
      env:
        REGISTRY : ${{ secrets.REGISTRY }}
        REPOSITORY: ${{vars.REPOSITORY}}
        IMAGE_TAG: ${{ github.sha }}
      run: docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
    - name: Configure AWS Credentials 
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{secrets.AWS_ROLE}}
        aws-region: us-east-1